data <- read.table("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?", stringsAsFactors = FALSE, col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
subData <- data[data$Date %in% c("1/2/2007", "2/2/2007"),]
gap <- as.numeric(subData$Global_active_power)
datetime <- strptime(paste(subData$Date, subData$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
vol <- as.numeric(subData$Voltage)
grp <- as.numeric(subData$Global_reactive_power)
submeter1 <- as.numeric(subData$Sub_metering_1)
submeter2 <- as.numeric(subData$Sub_metering_2)
submeter3 <- as.numeric(subData$Sub_metering_3)
par(mfrow = c(2,2))
plot(datetime, gap, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(datetime, vol, type = "l", ylab = "Voltage", xlab = "datetime")
plot(datetime, submeter1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datetime,submeter2, col="red", type = "l")
lines(datetime,submeter3, col="blue", type = "l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty=1, lwd=1)
plot(datetime, grp, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.copy(png, "plot4", width=480, height=480)
dev.off()